"""Field size

Revision ID: d04457731f25
Revises: 911bbd6654e5
Create Date: 2021-03-05 18:05:50.656513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04457731f25'
down_revision = '911bbd6654e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
