"""Relations

Revision ID: da0096fa43ce
Revises: 898da157b07b
Create Date: 2021-02-11 21:49:34.141224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0096fa43ce'
down_revision = '898da157b07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'albums', 'users', ['user_id'], ['id'])
    op.drop_column('albums', 'userid')
    op.drop_constraint('comments_postId_key', 'comments', type_='unique')
    op.create_foreign_key(None, 'comments', 'posts', ['postId'], ['id'])
    op.create_foreign_key(None, 'photos', 'albums', ['albumid'], ['id'])
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_userId_key', 'posts', type_='unique')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'userId')
    op.add_column('todos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'])
    op.drop_column('todos', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'user_id')
    op.add_column('posts', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_unique_constraint('posts_userId_key', 'posts', ['userId'])
    op.drop_column('posts', 'user_id')
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_unique_constraint('comments_postId_key', 'comments', ['postId'])
    op.add_column('albums', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'user_id')
    # ### end Alembic commands ###
