# Generated by Django 3.1.7 on 2021-04-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('website', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=32)),
                ('suite', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('zipcode', models.CharField(max_length=32)),
                ('geo_lat', models.CharField(max_length=32)),
                ('geo_lng', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('company_catchPhrase', models.CharField(max_length=128)),
                ('company_bs', models.CharField(max_length=128)),
            ],
        ),
    ]
