"""Posts table

Revision ID: 0020d58581cc
Revises: 57e830645add
Create Date: 2021-02-07 19:46:03.790479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0020d58581cc'
down_revision = '57e830645add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255),
                              server_default='', nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('users', sa.Column('user_class', sa.String(
        length=64), server_default='~', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_class')
    op.drop_table('posts')
    # ### end Alembic commands ###
