"""Posts table

Revision ID: 57e830645add
Revises: 36d79e240209
Create Date: 2021-02-07 17:11:12.249938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e830645add'
down_revision = '36d79e240209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_class', sa.String(length=64), server_default='~', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_class')
    # ### end Alembic commands ###
